# Generated by Django 5.1.3 on 2024-11-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_address_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialty',
        ),
        migrations.AddField(
            model_name='profile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='user.speciality'),
        ),
    ]
