# Generated by Django 5.1.3 on 2024-11-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rut',
        ),
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT'),
        ),
    ]
