# Generated by Django 5.1.3 on 2024-11-28 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_profile_rut_user_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='user.speciality', verbose_name='Especialidades'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='Desconocida', max_length=60, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(default='Desconocido', max_length=15, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Puntuación')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.profile', verbose_name='Perfil reseñado')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reseña')),
            ],
        ),
    ]
