# Generated by Django 5.1.3 on 2024-12-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_default.png', upload_to='media/'),
        ),
    ]
