# Generated by Django 5.1.3 on 2024-12-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profile_facebook_profile_instagram_profile_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='file',
            field=models.FileField(upload_to='credentials/', verbose_name='Archivo (PDF o Imagen)'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
