# Generated by Django 5.1.3 on 2024-12-10 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='user',
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_quotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
