# Generated by Django 5.1.3 on 2024-12-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_date_quotation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='recipient',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='received_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sender',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='sent_quotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
