# Generated by Django 5.1.3 on 2024-12-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_quotation_recipient_alter_quotation_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
