# Generated by Django 5.1.3 on 2024-12-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_quotation_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comuna',
            field=models.CharField(default='Santiago', max_length=50, verbose_name='Comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('Región de Arica y Parinacota', 'Región de Arica y Parinacota'), ('Región de Tarapacá', 'Región de Tarapacá'), ('Región de Antofagasta', 'Región de Antofagasta'), ('Región de Atacama', 'Región de Atacama'), ('Región de Coquimbo', 'Región de Coquimbo'), ('Región de Valparaíso', 'Región de Valparaíso'), ('Región Metropolitana de Santiago', 'Región Metropolitana de Santiago'), ('Región de O’Higgins', 'Región de O’Higgins'), ('Región del Maule', 'Región del Maule'), ('Región de Ñuble', 'Región de Ñuble'), ('Región del Biobío', 'Región del Biobío'), ('Región de La Araucanía', 'Región de La Araucanía'), ('Región de Los Ríos', 'Región de Los Ríos'), ('Región de Los Lagos', 'Región de Los Lagos'), ('Región de Aysén', 'Región de Aysén'), ('Región de Magallanes y de la Antártica Chilena', 'Región de Magallanes y de la Antártica Chilena')], default='Región Metropolitana de Santiago', max_length=50, verbose_name='Región'),
            preserve_default=False,
        ),
    ]
